### PR TITLE
feat: remove core patterns & registed custom categories

### LINKED ISSUE #61: Re-organise Pattern Library
### What problem does this address?

In the pattern library, we want to provide a theme-tight experience regarding patterns and page layouts. Currently in our themes, we follow the default/core pattern folder structure, and we also include many of the core patterns, which are inconsistent with the styles and layout of our theme. 

Additionally, we now keep our theme patterns in their own folder, which does not help with discoverability and workflow integration. 

current

### What is your proposed solution?

In order to create a safe and efficient environment for our users, we can:

- Remove the core patterns from the pattern library
- Organise the library with appropriate folders
- Distribute Theme patterns to these categories

new

This issue is also aligned with [Neve FSE library](https://github.com/Codeinwp/neve-fse/issues/89) direction
Also, let's keep in mind how this enriched library experience will interplay with the onboarding wizard.

cc @mghenciu 

### Will this feature require documentation? (Optional)

None

### PR DESCRIPTION
**Pull request by HardeepAsrani**
### Summary

As part of pattern library re-organization, this PR removes the core patterns and registers new pattern categories.

### Will affect visual aspect of the product

YES

### Test instructions

- Make sure Core Patterns don't load anymore.
- Make sure Raft patterns are registered properly.

Closes #61.

### CODE REVIEW

**Review by abaicus — APPROVED** [review]

**Comment by HardeepAsrani** [comment]
@JohnPixle I tested with the latest version of WordPress and I'm not able to reproduce that. Can you give me more info?

**Comment by HardeepAsrani** [comment]
@JohnPixle Thanks for the video. From your initial message, I had confused it with pattern and not pattern categories. I'll check if we can remove those as well.

**Comment by HardeepAsrani** [comment]
@JohnPixle After looking at it, there are few issues:

- If a customer has some patterns registered already those core categories, they will be removed and put to Uncategorized which isn't ideal.
- Second, there is no way to find which categories are just Core categories and not added by some plugin so we will either be maintaining a static list of Core categories or removing all of them, even ones registered by some plugins.

I'd go with not removing the categories. Let me know your thoughts.

**Comment by HardeepAsrani** [comment]
@JohnPixle Yes, to avoid breaking any existing site.

**Pull request merged**
