### PR TITLE
Adds secondary colors in theme.json + each palette

### LINKED ISSUE #64: Add secondary accent color
Similar to what [we did for Neve](https://github.com/Codeinwp/neve-fse/issues/92), we can introduce the addition of a secondary color in our palette. There is an existing PR that migrates Raft's color slugs to the ones that are used from our other themes, so we need to add the secondary color in the form of:

```
"slug": "ti-accent-secondary",
          "color": "#F5AABC",
          "name": "Secondary Accent"
```
Let me know if you need any clarifications!

### PR DESCRIPTION
**Pull request by mghenciu**
### Summary

Add the Secondary Accent color in the main theme.json file
and also added for each palette separately, the corresponding colors

### Will affect visual aspect of the product

NO

### Screenshots 

image

### Test instructions

- This changes are just in code. **We don't use the Secondary color anywhere, yet.**
- with this PR, the main palette should have a secondary color (in code). Same applies to all other color palettes.
- this can be checked by using the [Block Theme plugin](https://wordpress.org/plugins/create-block-theme/), which allows to see that each Color Palette and the Theme.json file have now a Secondary Accent Color

Closes #64  .

### CODE REVIEW

**Review by HardeepAsrani — COMMENTED** [review]
@JohnPixle Correct me if I'm wrong, but based on your comment the slug should be `ti-` not `raft-`, right?

**Comment by mghenciu** [comment]
> @JohnPixle Correct me if I'm wrong, but based on your comment the slug should be ti- not raft-, right?

YES, [there's a PR for that](https://github.com/Codeinwp/raft/pull/21), but I didn't changed them - because I am not sure if this won't break the build (without the changes from Andrei's PR).

**Comment by HardeepAsrani** [comment]
@mghenciu No, it shouldn't cause any issues really. It's a new color.

**Comment by mghenciu** [comment]
> @mghenciu No, it shouldn't cause any issues really. It's a new color.

Ok. then I'll update them to use `ti-`.

Thank you!

**Review by HardeepAsrani — APPROVED** [review]

**Pull request merged**
