### PR TITLE
chore: migrate colors to generic ones [closes #19]

### LINKED ISSUE #19: Migrate to the new color slugs we have on other block themes

### PR DESCRIPTION
**Pull request by abaicus**
Edit from Hardeep:

Testing: Make sure all the color variables are migrated after the activating the zip from this build and the theme looks the same before/after the zip file.

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@Codeinwp/design-team Here, can you help us to make sure this works as intended or any changes are required? Thank you!

**Comment by mghenciu** [comment]
> https://github.com/orgs/Codeinwp/teams/design-team Here, can you help us to make sure this works as intended or any changes are required? Thank you!

The build file from above is not available for download, in order to do the testing. Probably it expired.
And if I am not mistaking, this is more a dev chore - so nothing should be wrong/changed in terms of the UIX.

**Comment by irinelenache** [comment]
@abaicus @HardeepAsrani After adding this PR, without making any change, the homepage colors changed:

before the PR: https://github.com/Codeinwp/raft/assets/67897586/3989992f-4120-446e-9ca8-629d41b37d23

after the PR: https://github.com/Codeinwp/raft/assets/67897586/ac3fa0ae-9c31-4d24-9d58-5bd652176ec8

**Comment by HardeepAsrani** [comment]
@irinelenache Yes, that does happen at first but you can refresh the page and it should start to work like previously. Let me know how it goes for you.

**Comment by irinelenache** [comment]
@HardeepAsrani After a few refreshes the frontend looked fine 👍  In the editor though, the colors are still changed, i tried to clear the cache, use incognito and Browserstack.

You can check on this instance:
```
 Admin area URL: https://feignedexpert.s3-tastewp.com/wp-admin 
 Username: irinel 
 Password: 13aA8GzHtC4 
```

Let me know if there's any problem on my end 🙏

**Comment by HardeepAsrani** [comment]
Thanks @irinelenache, seems to be an issue.

Before we start working on it @abaicus, just wanted to know if this was a known side effect of this or there was work needed to fix this behavior, if you're aware?

**Comment by abaicus** [comment]
@HardeepAsrani I don't remember exactly what was happening here, unfortunately. IIRC, this was working ok when I submitted the PR initially. It might be that I just overlooked the bug in the editor.

**Comment by HardeepAsrani** [comment]
I've also replaced the color slugs in the existing patterns & templates: https://github.com/Codeinwp/raft/pull/21/commits/10fc68d20bfdca9f2d2b1560ec559a49e5fb5e86 - to avoid new users using old slugs.

**Comment by HardeepAsrani** [comment]
> You need to undo-the commit that replaces the slugs in the theme templates and patterns, that you did yesterday. 

@JohnPixle Thanks for your thoughts. I don't understand why to undo that commit if we aren't going to go ahead with. Let me know.

**Comment by HardeepAsrani** [comment]
@JohnPixle Then rest of the code in this PR is also not relevant as it replaces the raft- slug in options. 😄

**Pull request closed without merging**
