### PR TITLE
WooCommerce Compatibility

### PR DESCRIPTION
**Pull request by abaicus**

### CODE REVIEW

**Comment by JohnPixle** [comment]
@abaicus No rush with this, but when I tried to use the ZIP with WooCommerce activated I get a fatal error. Am I doing something wrong? 🥺

Screenshot 2022-11-21 at 12 09 50 PM

**Comment by JohnPixle** [comment]
@abaicus Works indeed, thanks!!

**Comment by JohnPixle** [comment]
@abaicus Hey! So, I did explore the Woo / Raft integration and came up with some input.

Overall, I think there is a lot of work that should be done from our side, if we really want to provide some meaningful (and future-proof) compatibility with Woo to our users. It's definitely not our fault, the issue stems from Woo's default styling and limited flexibility/ integration with the block editor and FSE overall.

Woo team must come up with a more block-friendly and flexible approach in styling, which I believe is something they should be working on (at least that's what they told me back in WCEU when I asked them 😂 )

I have a recorded [a quick loom](https://www.loom.com/share/302aa7bb14184310820c65b6ed554dc2) for you as a walkthrough on the issues I spotted.

The details for the demo where I made the experiments are below. Feel free to dive in.

```
 Admin area URL: https://wooraft.s4-tastewp.com/wp-admin 
 Username: pixle 
 Password: BLyYmQtAwXs 
```
### Suggestion

I was thinking if it would make sense for us to better proceed with the Raft update but without the Woo integration for now, and tackle the Woo integration separately. There will be a lot of CSS that we must add to Raft in order for Styles to be cohesive in the Woo context. I was really hyped about this, but the experience was disappointing so far 🥺.

Let me know what you think.

**Comment by abaicus** [comment]
@JohnPixle, I think you are right. It feels like WooCommerce has some work to do on block integration. Probably they are waiting for FSE to get to a more mature version. I think we can postpone this until things settle. 👍🏻

**Comment by mghenciu** [comment]
Hey, 
Is there an estimation about this in terms of a timeline, to get a better idea?

I am asking this because I am a bit worried about **Jaxon.** Because even if we have quite good download numbers (attached) per days, the retention doesn't look too good compared to our other themes released in the same period.
image

So my suggestion would be to at least go on the minimum things, like button Colors on Product page, colors on the Checkout in Dark mode, and so on - which should at least improve the overall quality of the theme, because ultimately we are positioning this theme as a **eCommerce theme**.
Screenshot 2023-01-17 at 10 14 18
Screenshot 2023-01-17 at 10 14 39
Screenshot 2023-01-17 at 10 14 58
Screenshot 2023-01-17 at 10 15 24
Screenshot 2023-01-17 at 10 16 13

**Comment by abaicus** [comment]
@mghenciu The issues you mentioned are also solved using WooCommerce Blocks instead of shortcodes - some things are in beta though, hence the postponing here:
fse test_checkout_
fse test_cart_

I think we should probably check it out.

**Comment by selul** [comment]
@mghenciu the fact that it has a spike is also related to the last update occurred in that day.

**Comment by mghenciu** [comment]
Thank you for the details @abaicus . I guess those changes should be made from code, right?
In case of the Products page, if I replace the Classic Template with the All Products block - will this be ok (attached a preview)? or it may cause some issues
Screenshot 2023-01-17 at 11 13 41

image


___

Got it, Marius. I was referring overall, the theme looks to have over 100-200 downloads per day, and we can monitor this long term, to see if the Thumbnails/niche attracts users - but something stops them from keeping it installed.

**Comment by selul** [comment]
@mghenciu for now, I would leave this for a while in order to have more data to prioritize the next moves, also good to bring to brainstorming to others.

**Pull request closed without merging**
